@startuml
'https://plantuml.com/class-diagram

class Calculator{
    main()
    start()
}

class CalculatorController{

}

javafx.Application <|-- Calculator

Calculator - CalculatorController

@enduml